###
POST http://localhost:8081/api/order
Content-Type: application/json

{
  "orderNumber": "INV-2021-0002",
  "skuCode": "V002",
  "price": 2000,
  "quantity": 20
}

###
GET http://localhost:8081/api/order
Content-Type: application/json


###
GET http://localhost:8081/api/order/1

###
GET http://localhost:8081/api/order/2